### ISSUE TITLE
No available timestamps since 02/05

### ISSUE THREAD

**Issue by ghost** [poetapp/frost-api#1018]
Hello,

It seems that some of recent timestamps are not shown in the [explorer](https://explorer.poetnetwork.net/issuers/data:;base64,eyJhbGdvcml0aG0iOiJFZDI1NTE5U2lnbmF0dXJlMjAxOCIsInB1YmxpY0tleSI6IkZRcXVqOWV2ZlBxY1RaWVBQUHhpUjMza1JHUXpzcjZQNDhSSE1VS2ZvUWJOIn0=) (already tried multiple browsers). @lautarodragan 

Can you confirm if this is a bug?

For example:
https://explorer.poetnetwork.net/works/be144206953c7d131b6cf0c9e8be5db56caffee2baf1d0dc64cf1137352c9508

https://explorer.poetnetwork.net/works/b6c86c17fec6cdcb4ba64d9020cbb57906c6e29c04fc586cb01f77e1940dd003

**Comment by ghost** [comment]
@wdavidturner @lautarodragan @WesleyCharlesBlake Hello, can someone confirm the death of this project? We need to move on.

**Comment by tylev** [comment]
hi, the timestamp issues are because our Poet nodes keep running out of BTC to pay the network fees... since the halving and increased fee rates, we haven't optimized well. We're looking into some solutions as well as topping up the BTC balances.

**Comment by ghost** [comment]
@tylev thanks for the information. What  are we supposed to do as early adopters of po.et API? 

Update, po.et removed.
