### ISSUE TITLE
Improve login token

### ISSUE THREAD

**Issue by wzalazar** [poetapp/frost-api#55]
Now, the login token has expiration time in 24h and it has not the ability to renew.

https://github.com/poetapp/frost-api/blob/master/src/api/Tokens.ts#L18

We need to implement a mechanism with the goal to renew the login token

Some tasks suggested

- [ ] Extend time to live
- [ ] Change the property ```renewable``` to ```true```
- [ ] Create method in Vault with the goal to renew login token
- [ ] Identify when is the moment we have to renew the token

**Comment by lautarodragan** [comment]
We can live without renewable and handle the session timeout with better UX in Explorer for now.

Integrations should avoid using Login Tokens.
