### ISSUE TITLE
Integration Test: Check Frost works fine after Vault Root token rotation

### ISSUE THREAD

**Issue by wzalazar** [poetapp/frost-api#693]
The goal is to create an integration test to cover these cases when the Vault Root token is rotated

After rotating the Vault Root token the user should can continue to do this actions:

- Create a new account
- Login
- Create API Tokens Mainnet/Testnet
- Get API Tokens Mainnet/Testnet
- Publish Work Mainnet/Testnet
- Get Works Mainnet/Testnet

Keep in mind that the user could be using the system when the Root token is rotated.

**Comment by lautarodragan** [comment]
Superseded by https://github.com/poetapp/frost-api/issues/693
